services:
  service-catalog-api:
    build:
      context: .
    container_name: service-catalog-api
    ports:
      - "8200:8200"
    environment:
      # absolute inside-container path; will be mounted to your host folder
      DATABASE_URL: "sqlite:////data/service_catalog.db"
    volumes:
      # bind mount to your local sc_data folder (make sure it exists!)
      - ./sc_data:/data
    # ensure the directory exists before the app imports and connects
    command: >
      sh -c "mkdir -p /data &&
             python -m uvicorn app.main:app --host 0.0.0.0 --port 8200 --reload"
